### ISSUE TITLE
Weather and flood data in space and time

### ISSUE THREAD

**Issue by jwagemann** [vismethack/challenges#5]
In the [SEE-MHEWS](https://public.wmo.int/en/projects/see-mhews-a) project we have developed a new interface to visualise meteorological and hydrological forecast data for regions and catchments in South-East Europe. We need help in improving the visualisation of the data and ideas on how the user can interact with the data as well as animations in space and time.

**Comment by nguyenquangchien** [comment]
That sounds interesting, but apparently I cannot access the system with my ECMWF account.

**Comment by climaterobin** [comment]
I would also be interested to work on this. The SEE-MHEWS link doesn't work for me either.

**Comment by jwagemann** [comment]
Hi @climaterobin and @nguyenquangchien . Thanks for your interest in the challenge - I updated the link, which should now be accessible.

**Comment by climaterobin** [comment]
Thanks. That webpage mostly seems to be a written explanation of the project. Do you have a demo version of the software or any images so we can get an idea of what it looks like?

**Comment by jwagemann** [comment]
Hello @climaterobin and @nguyenquangchien Apologies, but we unfortunately have to withdraw this challenge from the hackathon. I will close this issue.
